server:
  port: 9003
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: AGENT-SERVICE
        uri:
          lb://AGENT-SERVICE
        predicates:
        - Path=/agent/**
        
      - id: HUB-SERVICE
        uri:
          lb://HUB-SERVICE
        predicates:
        - Path=/hub/**
        
        